### ISSUE TITLE
Blurry text on chrome

### ISSUE THREAD

**Issue by lulupointu** [TimWhiting/dart_pad_widget#3]
Hi, thanks for the plugin !

I wanted to let you know that on chrome, the text in the DartPad widget gets blurry depending on the size of the window (not the size of the widget, the actual size of the window, which might displace the widget from 1/2 pixel maybe?)

Anyway, here is an example:
*Blurry:*
![image](https://user-images.githubusercontent.com/5128921/111887290-480fd000-89d4-11eb-8746-a71cab93f382.png)

*NOT blurry:*
![image](https://user-images.githubusercontent.com/5128921/111887296-5231ce80-89d4-11eb-98eb-4b2c30c1f2c8.png)

I can't tell what change in the window size lead to this issue, in works with any window size by just changing the size of a few pixels.

Also note that I cannot reproduce this behavior in Firefox, only in chrome.

Also I did display rich bellow the DartPad widget and it does not get blurry.

**Comment by lulupointu** [comment]
Well actually I just tried embedding a dartpad directly in a webview and the same happens so I guess its not your fault.

If you have an idea on how to solve this/where to find a solution I would love to hear it!

In any case, feel free to close the issue

**Comment by TimWhiting** [comment]
All it is using under the hood is an html element with the embedded version of dartpad from their repo.

See [this embedding guide](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide).

So it shouldn't be anything related to Flutter. And I have no idea why that would be happening. I'll close unless you find something that suggests this library is at fault, but I would be surprised if that was the case.
